language: php

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=Seo
    - REQUIRE="cakedc/search:master"
    - DB=mysql CAKE_VERSION=2.4

  matrix:
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - pear config-set auto_discover 1
  - pear uninstall phpunit/PHPUnit
  - pear channel-update pear.phpunit.de
  - pear install pear.phpunit.de/PHPUnit-3.7.0
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - git clone -b master https://github.com/CakeDC/search.git --depth 1 ../cakephp/app/Plugin/Search

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
